[package]
name = "clang-format-action"
version = "0.1.0"
authors = ["Andrew Gaspar <andrew.gaspar@outlook.com>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
rayon = "1.3.0"

[dependencies.clap]
version = "2.33.0"
default-features = false